blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/franckferman/gentoo-post-install/security/advisories/new
    about: Please report security issues privately. Use the private security advisory link below.
